In [1]:
import spacy
spacy.prefer_gpu()
nlp = spacy.load("da_core_news_trf")

/Users/rakul/Desktop/cs/5sem/msc/cph-menu-finder/.venv/lib/python3.12/site-packages/torch/jit/_script.py:1491: FutureWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(

In [2]:
import pandas as pd
from config import WOLT_DATA_DIR

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 60)

In [3]:
AREA = "vesterbro"

venues = pd.read_csv(WOLT_DATA_DIR / AREA / "venues.csv")
items_raw = pd.read_csv(WOLT_DATA_DIR / AREA / "items.csv")

In [4]:
def normalise(s: pd.Series) -> pd.Series:
    return s.lower().strip()

items_raw.description = items_raw.description.fillna("")
items_raw.description = items_raw['description'].apply(normalise)
items_raw

,wolt_id,venue,category,item,description,price_dkk
0,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Klassisk okseburger,"sesambolle med fyld af oksebøf, dressing, ketchup, icebe...",88.0
1,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Hovedretter,En halv grillkylling,,108.0
2,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Maxi Cheeseburger,"briochebolle med fyld af ca. 300 grams oksebøf, ost, sal...",128.0
3,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Gorgonzola,"tomatsauce, ost, gorgonzola, champignon, løg og rucola.",115.0
4,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Caprese,"tomatsauce, ost, kødstrimler, paprika og bearnaisesauce.",115.0
...,...,...,...,...,...,...
9962,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Quesadillas,Mini Corn Quesadilla,"corn tortilla, ost, carnitas pork eller kylling, salsa m...",65.0
9963,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Burritos,Burrito - Block Party BBQ 🌶️,"hvede tortilla, ris, raw slaw, sorte bønner, dit valg af...",145.0
9964,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Børnemenu,Kids Bowl,"ris, romaine, barbacoa beef/grillet kylling/veggie strip...",89.0
9965,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Dips,BBQ Sauce,.,10.0
9966,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Sodavand,Faxe Kondi 33cl,.,35.0

In [5]:
for d in items_raw.description:
    print(d)

sesambolle med fyld af oksebøf, dressing, ketchup, icebergsalat, løgringe, tomat og agurk.

briochebolle med fyld af ca. 300 grams oksebøf, ost, salat, tomat, løg og agurk.
tomatsauce, ost, gorgonzola, champignon, løg og rucola.
tomatsauce, ost, kødstrimler, paprika og bearnaisesauce.
tomatsauce, ost, kylling, pepperoni og paprika.
tomatsauce, ost, spinat, oliven, gorgonzola, champignon og hvidløg.
serveret med pommes frites, salat og remoulade.
tomatsauce, ost, kebab, kylling, pepperoni eller kalkunskinke, salat og dressing.
oksekødsret serveret med pommes frites, hummus, salat og brød.

tyrkisk brød med fyld af valgfri protein, salat, tomat, agurk og creme fraiche.
box med fyld af kebab, salat, pommes frites og dressing.
tomatsauce, ost og kalkunskinke.
serveret med pommes frites, salat, dressing og remoulade.

tomatsauce, ost, kebab og champignon.
græsk bøf med stegte løg, pommes frites, jalapeños, salat og bearnaisesauce.
tomatsauce, ost, rejer, tun, paprika og løg.
tomatsauce, ost, hakket oksekød, paprika og cocktailpølser.
falafel ret serveret med pommes frites, hummus, salat og brød.
tomatsauce, ost, shawarma, pepperoni og jalapeños.
serveret med pommes frites, salat, dressing og bearnaisesauce.


tomatsauce, ost, kødstrimler, champignon og løg.
serveret med pommes frites, hummus, salat og brød.
briochebolle med fyld af ca. 300 grams oksebøf, bacon, ost, salat, tomat, løg, agurk og thousand island dressing.
tomatsauce, ost, lammekød, champignon, jalapeños, pesto og paprika.
serveret med pommes frites, hummus, salat og brød.

tomatsauce, ost, kylling, pesto, tomat og rucola.
tomatsauce, ost, kylling, kalvebacon, ananas og paprika.
tomatsauce, ost, pepperoni, gorgonzola og hvidløg.
tomatsauce, ost, ananas og kalkunskinke.
tomatsauce, ost, shawarma, kalvebacon og champignon.
tomatsauce, ost, hakket oksekød, chili, pepperoni, løg og jalapeños.
tomatsauce, ost, kødstrimler, champignon, paprika og oliven.
briochebolle med fyld af falafel, tomat, agurk, mayonnaise, ketchup og salat.
sesambolle med fyld af oksebøf, kalvebacon, dressing, ketchup, icebergsalat, løgringe, tomat og agurk.
almindelig burger serveret med pommes frites og en valgfri 0,33 l sodavand.
tomatsauce, ost, champignon, paprika, løg, ananas og artiskok.

briochebolle med fyld af ca. 300 grams oksebøf, salat, tomat, løg og agurk.
sesambolle med fyld af oksebøf, jalapeños, dressing, ketchup, icebergsalat, løgringe, tomat og agurk.

briochebolle med fyld af vegetarisk bøf, tomat, agurk, mayonnaise, ketchup og salat.
fladbrød med fyld af valgfri protein, salat, tomat, løg og dressing.
græsk salat med fetaost og oliven, serveres med brød.
tomatsauce, ost, pepperoni, kalvebacon, kalkunskinke og æg.
briochebolle med fyld af oksebøf, kalvebacon, tomat, agurk, mayonnaise, ketchup og salat.
briochebolle med fyld af oksebøf, tomat, agurk, mayonnaise, ketchup og salat.
en halv kylling serveret med pommes frites, salat, jalapeños og valgfri dyppelse.
tomatsauce, ost, falafel, soltørret tomater, oliven, gorgonzola og rucola.
tomatsauce, ost, kalkunskinke, shawarma, paprika og hvidløg.

hakket bøf med stegte løg, champignon, pommes frites, salat og bearnaisesauce.
tomatsauce, ost og pepperoni.
tomatsauce, ost, hakket oksekød, pepperoni og champignon.
tomatsauce, ost, kødsauce og løg.
tomatsauce, ost, kalkunskinke og champignon.
tomatsauce, ost, cocktailpølser, pepperoni og champignon.


tomatsauce, ost og valgfri protein.
sesambolle med fyld af oksebøf, ost, dressing, ketchup, icebergsalat, løgringe, tomat og agurk.
briochebolle med fyld af 2x oksebøf, tomat, agurk, mayonnaise, ketchup og salat.
tomatsauce og ost.
tomatsauce, ost, pepperoni, kødstrimler og gorgonzola.
sandwich med fyld af valgfri protein, smeltet ost, salat, tomat, løg og. valgfri dressing.
tomatsauce, ost og kalkunskinke.
tomatsauce, ost, kødsauce og spaghetti.
tomatsauce, ost, kalkunskinke, kalvebacon, løg og æg.
serveres med pommes frites og en valgfri 0,33 l sodavand.
hjemmelavet pitabrød med fyld af valgfri protein, salat, tomat, løg og valgfri dressing.
tomatsauce, ost, gorgonzola, løg, artiskok, oliven og rucola.
tomatsauce, ost, kødsauce, jalapeños, pepperoni og chili.
briochebolle med fyld af kyllingebøf, tomat, agurk, mayonnaise, ketchup og salat.
briochebolle med fyld af ca. 300 grams oksebøf, oksebacon, salat, tomat, løg og agurk.

briochebolle med fyld af oksebøf, ost,  tomat, agurk, mayonnaise, ketchup og salat.
hønsesalat med grøn crudité, asparges, sprødt kyllingeskind og karse (g + l + æg + selleri + sennep)
økologisk myntebrus fra naturfrisk, 25cl
gulerødder, knoldselleri, blomkål, eddike, sukker, mayonnaise (rapsolie, æg, dijonsennep, æbleeddike, salt, peber), løg chili, sennep, gurkemeje, paprika, maizena
5,5% 0,33 l
rødbeder, eddike, anis, sennepsfrø, sukker, kanel, allehånde og peber
riesling 11,5% - 0,75 l
avocado med citronemulsion, kål, syltede salatløg og rugchips (g + l + æg)
kartoffel med sæsonens emulsion og grønt, syltede løg, sprød kartoffel og urter (g + l + æg + sennep)

pålægschokolademad med mørk chokolade fra friis-holm, flødekaramel, blåbærkompot, vaniljecreme og mandler (g + l + æg + nødder)
3 stk. smørrebrød: avocado, hønsesalat og roastbeef.
3 stk. smørrebrød: kartoffel, gule beder og avocado.
svampetoast med svampe fra funga farm, marsala, æbler, creme fraiche, citronskal og persille (g + l + sennep)
cremet æggesalat med cornichoner, bladselleri og purløg.
dronning victoria-ost fra nørup mejeri med sæsonens kompot, ristede mandler og kørvel (g + l + nødder)
14,5%  - 37,50 cl
gammeldags modnede sild med karrysalat, forårsløg, æbler og ristede boghvedekerner (g + l + æg)
varmrøget laks, bagt laks, cremefraiche, past. æggeblomme, olie, capers, dild og citron
skinke og ost med agurk, skalotteløgsrelish, hjertesalat og sennepscreme.

de angelis rosso piceno  - 14,5%  - 0,75 l
cremet hønsesalat med bacon, æbler, drueagurker og selleri.
herslev, 0,3% 0,33l
rørt oksetatar med sæsonens emulsion og grønt, forårsløg, sprød kartoffel og karse (g + l + æg + sennep)
frikadeller af kalv og flæsk med kartoffelsalat, radiser og urter
paneret og smørstegt rødspætte med rejesalat, bagt selleri, syltede salatløg, røget paprika og dild (g + l + æg + selleri)
agurker, hvidvinseddike, sukker og vand
økologisk æblemost fra naturfrisk, 27,50cl
mandelkage med citrussirup, blå birkes, vaniljecreme og ristede mandler (g + l + æg + nødder)
hønsesalat på smørristet surdejsbrød med syltede rødløg, baconcrumble og urter. (g + l + æg + sennep)
4 stk. smørrebrød: kartoffel, rødspætte, hønsesalat og trifli.
agurk og avocado med friskost, jalapeño, tomat, myntecreme og mandler.
aamanns, herslev - 5% 0,33l
sild, sukker, eddike, løg, allehånde. 3 store fileter.
5,0% 0,33 l
laksetatar med æbler, fennikel, rugkrummer og dild (g + l + æg + sennep)

gule beder med estragonemulsion, forårsløg glaskål, syltede salatløg og ristede boghvedekerner (g + l + æg + sennep)
trifli med sæsonens bær/frugtkompot, mascarponecreme, polynesisk vanilje og mandelcrumble (l + nødder)
koldrøget laks fra hiddenfjord med friskost, agurk, olivenolie og ristede mandler.
paneret og smørstegt rødspætte med rodfrugtremoulade, syltede rødløg og urter (g + l + æg + selleri)
roastbeef med bearnaisecreme, let bagte tomater, syltede agurker og sprød kartoffel (g + l + æg)
håndpillede rejer på smørristet surdejsbrød med tomatmayonnaise, syltede salatløg, tomatpulver og urter. (g + l + æg)
høns, citron, sennep, gulerødder, selleri
roastbeef med bearnaise, syltede agurker og sprød kartoffel.
æg og håndpillede rejer med tomatemulsion, cherrytomater, bladselleri og ristede mandler (g + l + æg + sennep + nødder)
chokolademousse med 60% valrhona oriado chokolade og kakaonibs (l + æg)
riesling 11,5% - 37,50 cl
rapsolie, æg, dijonsennep, æbleeddike, salt, peber

sprøde krydrede chips af kikærtemel, serveret med en trio af livlige og syrlige chutneys.
vælg selv hvilken suppe du ønsker. vælg mellem linse, kylling, tomat eller vegetar.
sprøde samosa med krydrede kartofler og ærter toppet med lækre syrlige og krydrede kikærter, tomater, løg, yoghurt, tamarind og mynte chutney og et drys chat massala.
mosede kartofler kombineret med friske grønne ærter, et strejf af knust chilli med aromatiske løg, harmoniseret med en blanding af karrykrydderier, tilberedt som velsmagende bøffer og stegt på panden.
hjemmelavet paneer og grøntsager med forfriskende urter, friturestegt i kikærtemel, serveres med køldende yoghurt.
udvalgte grøntsager stegt i varme traditionelle orientalske krydderier, hvilke resulterer i en sprøde tekstur og gylden farve.
saftige og møre grillede lammekoteletter marineret i en blanding af yoghurt, hakkede krydderier og krydderurter, som mørner kødet og skaber en let røget og forkullet smag.
grillet frisk paneer marineret i krydret yoghurt med tomat, løg og peberfrugter.
sprødstegt fisk marineret i syrlig citron og aromatiske varme krydderier.
mørt tandoori grillet lammekød marineret i aromatiske kashmiri krydderier og yoghurt, serveres med løg og tomater.
kylling marineret i en blanding af    aromatiske krudderier med karamelliserede løg og saftig tomater.
krydret hakket oksekød kebab marineret i punjabi krydderier, ingefær, hvidløg, lime og frisk koriander.
butter chicken med ris, salat og pommes frites.
krydret saftig lammekød simret i en robust ingefær, løg og i en rig tomatsovs.

ris eller naanbrød skal bestilles separat.
grillet lammekød marineret i punjabikrydderier, serveres i en lækker cremet tomatsovs.

ris eller naanbrød skal bestilles separat.
tandoori lammekød, marineret i en blanding af  krydderier, omfavnet af en cremet fløde og smørsovs og langtidskogt til perfektion.

ris eller naanbrød skal bestilles separat.
saftig lammekød i en lækker krydret cremet cashewsovs, fyldt med den varme aroma fra garam massala og den rige smag af frisk fløde.

ris eller naanbrød skal bestilles separat.
saftig lammekød tilberedt i en mild karry med finthakket spinat og aromatiske urter. denne ret forener lammets fyldige smag med den milde rige smage af spinat.

ris eller naanbrød skal bestilles separat.
saftig lammekød tilberedt med en blanding af sagte løg, aromatiske urter og saftige okra. lammets rige fyldige smag komplementerer perfekt den subtile søde smag af okra.

ris eller naanbrød skal bestilles separat.
delikat oksekød simret i en syrlig karry med traditionelle krydderier med frisk hvidløg, ingefær og tomater der giver en skrap kontrast.

ris eller naanbrød skal bestilles separat.
mørt oksekød tilberedt i en velkrydret kashmiri karry hvor kartoflerne optager den rige sovs og bidrager med et fyldig og tilfredstillende element.

ris eller naanbrød skal bestilles separat.
saftige oksekød simret i en lækker krydret karry, fyldt med blanding af aromatiske urter og velsmagende krydderier.

ris eller naanbrød skal bestilles separat.
saftig kylling stegt med aromatisk ingefær, sprøde peberfrugter og æg, simmeret i en livlig og velsmagende sovs.

ris eller naanbrød skal bestilles separat.
saftig tandoori grillet kylling, mildt krydret og serveret i en rig, cremet og velsmagende smørsovs med en strejf af sødme.

ris eller naanbrød skal bestilles separat.
krydret kylling i en tyk cremet kokos karrysovs, beriget med udvalgte urter for en velsmagende ret.

ris eller naanbrød skal bestilles separat.
saftig kylling i en mild karry med håndhakkede krydderier, der skaber en rig og velsmagende ret.

ris eller naanbrød skal bestilles separat.
grillet kylling serveret i en krydret cremet karrysovs med aromatiske krydderier for en appetitvækkende og rig smag

ris eller naanbrød skal bestilles separat.
kongerejer marineret i chili og lime, tilberedt i en rig cremet sovs med smør, fløde og kokosmælk, tilberedt med velsmagende krydderier som resultere i en luksuriøs skaldyrsmag.

ris eller naanbrød skal bestilles separat.
krydrede tandoori kongerejer marineret i eddike, citron, ingefær og hvidløg for en rigt smagfuld og zesty ret.
ris eller naanbrød skal bestilles separat.
grillede kongerejer i en rigt puré af hvidløg, ingefær, tomat og løg, serveres i en cremet karrysauce.

ris eller naanbrød skal bestilles separat.
saftige kongerejer i tyk krydret sovs med saftige tomater, ingefær, hvidløg og velsmagende løg.

ris eller naanbrød skal bestilles separat.
urteinfuseret vegetablisk kofta med frisk paneer i en mild cremet karrysovs, tilberedt af skrape aromatiske krydderier.

ris eller naanbrød skal bestilles separat.
friske krydrede ærter parret med smøragtigt hjemmelavet paneer der leverer en robust og velsmagende ret.

ris eller naanbrød skal bestilles separat.
hjemmelavet paneer med friske urter,  tilberedt med skrape orientalske krydderier i en delikat cremet sauce med en let luftig tekstur.

ris eller naanbrød skal bestilles separat.
krydrede kikærter med stærke og aromatiske punjabi krydderier, forstærket med friske koriander og pyntet med en strejf citron for en ekstra dimension af smag.

ris eller naanbrød skal bestilles separat.
frisk blomkål og møre kartofler kogt i en krydret tomatpuré med aromatiske ingefær og spidskommen der giver en sagtig og robust smag

ris eller naanbrød skal bestilles separat.
pandestegte linser med frisk aromatiske hvidløg og ingefær,tilberedt i en blanding af krydderier som giver en rig og skrap smag

ris eller naanbrød skal bestilles separat.
okra med en syrlig blanding af spidskommen med lime, kogt med løg og søde tomater for en smagfuld og zesty ret.

ris eller naanbrød skal bestilles separat.
fortyndet pisket yoghurt enten med salt eller sukker.

risret med lam.
risret med rejer.
risret med grøntsager.
risret med kylling.
risret med lam.
1 x paneer tikka
1 x raita og chutney
1 x lamb spinach
1 x chicken achari
1 x barbari dal tarka
1 x pilau rice
1 x tandoori garlic naan
1 x samosa
1 x raita og chutney
1 x nargisi beef bhuna
1 x chicken handi
1 x malai kofta
1 x plain rice
1 x tandoori naan
1 x onion bhaji
1 x raita og chutney
1 x butter chicken
1 x lamb rogan josh
1 x aloo gobi
1 x pilau rice
1 x tandoori garlic naan
1 x aloo tikki
1 x raita og chutney
1 x punjabi bhindi massala
1 x lahori channa massala
1 x paneer makhani
1 x vegetable rice
1 x tandoori naan
1 x aloo tikki
1 x raita og chutney
1 x punjabi bhindi massala
1 x lahori channa massala
1 x paneer makhani
1 x vegetable rice
1 x tandoori naan
1 x tandoori lamb tikka
1 x chicken balti
1 x nawabi malai king prawn
1 x palak paneer
1 x pilau ris
1 x tandoori naan
1 x chutney
1 x raita
1 x chicken tikka
1 x lamb tikka massala
1 x butter chicken
1 x shahjahani paneer tikka massala
1 x vegetable ris
1 x tandoori garlic naan
1 x chutney
1 x raita
1 x al-diwan mixed grill
1 x king prawn tandoori
1 x sultani lamb butter tikka
1 x chicken tikka masala
1 x paneer jalfrezi
1 x hydrabadi vegetable biryani
1 x tandoori naan
1 x chutney
1 x raita
indisk lager øl













dampet langkornet basmatiris
langkornet basmatiris kogt med ærter og krydderier
langkornet basmatiris med udvalgte grøntsager.
youghurt baseret salat med forskellige krydderier
husets specialitet

bombay ipa - classic - new york lager - king´s county brown ale



valgfri protein, salat, rødkål, rødløg, tomat, agurk og hjemmelavet yoghurt dressing. serveres med pommes frites, mayo og en gazoz 0,33 l.
valgfri protein, salat, rødkål, rødløg, tomat, agurk og hjemmelavet yoghurt dressing. serveres med pommes frites, mayo og en gazoz 0,33 l.
valgfri protein, pommes frites, salat, rødkål, rødløg, tomat, agurk og hjemmelavet yoghurt dressing. serveres med mayo og en gazoz 0,33 l.


valgfri protein, salat, rødkål, rødløg, tomat, agurk og hjemmelavet yoghurt dressing.
valgfri protein, salat, rødkål, rødløg, tomat, agurk og hjemmelavet yoghurt dressing.
valgfri protein, pommes frites, salat, rødkål, rødløg, tomat, agurk og hjemmelavet yoghurt dressing.
nudelsalat med oksekod & forårsruller grontsager, urter,ristet log og fiskesauce.
3 x forårsruller med hakket gris, glasnudler og grøntsager på salat og mynte. serveres med fiskesauce.
3 x hakket kylling og grøntsager. serveres med soja sauce.
2 x  friske ruller med tigerrejer, risnudel, koriander & mynte. hoisin-peanuts sauce
4 x wontons med grontsager og soja .sauce.
4 wontons, 4 friske ruller, 4 vietnamesiske ruller, 4 samosa
saucer: soja og hoisin-peanuts sauce
spicy oksekød,  risnudel, sprøde grøntsager, urter, peanuts, friterede løg og fiskesauce.
risnudel, sprøde grøntsager, urter, peanuts, friterede løg og fiske sauce. serveres med vietnamesiskeruller.
risnudel, sprøde grøntsager, urter, peanuts, friterede løg og fiskesauce. serveres med med citrongræs-gris.
citrongres-gris, ris, agurk, frisk spidskål, urter og gulerodspickles.
spicy oksekødssalat, sprøde salat & urter, med ris.
karrykylling, gulerødder, bønnespirer, forårsløg og ris.
nudelsalat med vegetarisk wontons, risnudel,  sprode grontsager, urter, peanuts og sojasauce.



med pommes frites og valgfri protein.
hjemmelavet durum m. valgfri protein, pommes frites og valgfri sodavand.
chili cheese tops serveret med mayo.
mozzarella sticks serveret med mayo.
onion rings serveret med mayo.
serveret med mayo.
serveres med hummus eller tzatziki.
kebab ret med pomes frites, salat med dressing, tzatziki og hummus.
kylling ret med pommes frites, salat med dressing, tzatziki og hummus.
falafel ret med pommes frites, salat med dressing, tzatziki og hummus.
börek med ost og spinat.









hjemmelavet pita m. valgfri protein, pommes frites og valgfri sodavand.
bowl bestående af pommes frites, valgfri protein, valgfri dressing, tzatziki og hummus.
hjemmelavet durum m. valgfri protein.


hjemmelavet pita m. valgfri protein.



serveres med brød og smør.
grøn salat med ærter, tomat, gulerødder og oliven. serveres med dressing.
serveres med valgfri dip.
toppet med mozzarella og løg. serveres med valgfri dip.
serveres med valgfri dip.
pepperoni, oksekød, skinke, champignon, løg og rød peber.
pepperoni, oksekød, skinke, champignon, løg og rød peber.
rejer, tun og champignon.
rejer, tun og champignon.
skinke og champignon.
skinke og champignon.
pepperoni, rød peber og champignon.
pepperoni, rød peber og champignon.
pepperoni, oksekød, skinke og bacon.
pepperoni, oksekød, skinke og bacon.
kebab, tomat, agurk, iceberg og creme fraiche.
kebab, tomat, agurk, iceberg og creme fraiche.
champignon, ananas, rød peber, løg, majs, ærter og oliven.
champignon, ananas, rød peber, løg, majs, ærter og oliven.
mozzarella og tomatsauce.
mozzarella og tomatsauce.
oksekød, pepperoni, løg, champignon og bbq sauce.
oksekød, pepperoni, løg, champignon og bbq sauce.
bacon, løg og majs.
bacon, løg og majs.
oksekød, jalapenos og løg.
oksekød, jalapenos og løg.
skinke og ananas.
skinke og ananas.
kylling, rød peber og løg.
kylling, rød peber og løg.
pepperoni og ekstra pepperoni.
pepperoni og ekstra pepperoni.
oksestrimler, champignon og rød peber.
oksestrimler, champignon og rød peber.
toppet med blandet salat, ærter, majs, tomat, revet gulerødder og oliven. vælg mellem creme fraiche eller thousand island dressing.
2 stykker rødspættefileter serveret med blandet salat, pommes frites og remoulade.
toppet med parmesan.
kylling i tomatsovs. toppet med parmesan.
serveret med blandet salat, pommes frites eller bagt kartoffel.
300 gr serveret med grøn salat, pommes frites eller bagt kartoffel.
serveres med grøntsager, salat, pommes frites eller bagt kartoffel.
oksekød serveret med salat, løg, tomat, agurk og creme fraiche dressing.
oksekød serveret med salat, løg, tomat, agurk og creme fraiche dressing.
oksekød i box serveret med pommes frites, salat, løg, tomat, agurk og creme fraiche.
klassisk burger med 150 gram bøf af oksekød, tomat, løg, blandet salat og ketchup.
burgerbolle med 150 gram bøf af oksekød, bacon, cheddarost og bbq sauce.
burgerbolle med 150 gram bøf af oksekød, cheddarost, jalapeños, løgringe og chillimayo.
burger bolle med bøf af sprød kylling, cheddarost og mayo.
burgerbolle med rødspættefilet og remoulade.
burgerbolle med bøf af grøntsager, cheddarost og mayo.
serveres med parmesan.

In [ ]:
def lemmatize_doc(doc) -> list[str]:
    return [ t.lemma_ for t in doc if not t.is_stop and not t.is_punct and t.pos_ != "VERB" ]

items_raw["description_lemmatized"] = [ lemmatize_doc(doc) for doc in nlp.pipe(items_raw.description, batch_size=64) ]

In [21]:
items_raw.rename(columns={'lemmas': 'description_lemmatized'}, inplace=True)
items_raw.head(10)

,wolt_id,venue,category,item,description,price_dkk,description_lemmatized
0,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Klassisk okseburger,"sesambolle med fyld af oksebøf, dressing, ketchup, icebe...",88.0,"[sesambolle, fyld, oksebøf, dressing, ketchup, icebergsa..."
1,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Hovedretter,En halv grillkylling,,108.0,[]
2,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Maxi Cheeseburger,"briochebolle med fyld af ca. 300 grams oksebøf, ost, sal...",128.0,"[briochebolle, fyld, cirka, 300, gram, oksebøf, ost, sal..."
3,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Gorgonzola,"tomatsauce, ost, gorgonzola, champignon, løg og rucola.",115.0,"[tomatsauce, ost, gorgonzola, champignon, løg, rucola]"
4,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Caprese,"tomatsauce, ost, kødstrimler, paprika og bearnaisesauce.",115.0,"[tomatsauce, ost, kødstrimler, paprika, bearnaisesauce]"
5,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Lazio,"tomatsauce, ost, kylling, pepperoni og paprika.",110.0,"[tomatsauce, ost, kylling, pepperoni, paprika]"
6,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Spinat ( V),"tomatsauce, ost, spinat, oliven, gorgonzola, champignon ...",117.0,"[tomatsauce, ost, spinat, oliven, gorgonzola, champignon..."
7,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Børnemenuer,Børne Chicken Dipper (6 stk),"serveret med pommes frites, salat og remoulade.",88.0,"[pommes, frites, salat, remoulade]"
8,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Sofus,"tomatsauce, ost, kebab, kylling, pepperoni eller kalkuns...",120.0,"[tomatsauce, ost, kebab, kylling, pepperoni, kalkunskink..."
9,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Hovedretter,Kebabret,"oksekødsret serveret med pommes frites, hummus, salat og...",133.0,"[oksekødsret, pommes, frites, hummus, salat, brød]"

In [25]:
from googletrans import Translator

translator = Translator()

langs = await translator.detect(items_raw.description)

In [29]:
unique_descs = [ d for d in items_raw.description.unique() ]
detections = await translator.detect(unique_descs)

lang_by_desc = { d: det.lang for d, det in zip(unique_descs, detections) }
confidence_by_desc = { d: det.confidence for d, det in zip(unique_descs, detections) }

items_raw["lang"] = items_raw.description.map(lang_by_desc)
items_raw["lang_confidence"] = items_raw.description.map(confidence_by_desc)
items_raw

,wolt_id,venue,category,item,description,price_dkk,description_lemmatized,lang,lang_confidence
0,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Klassisk okseburger,"sesambolle med fyld af oksebøf, dressing, ketchup, icebe...",88.0,"[sesambolle, fyld, oksebøf, dressing, ketchup, icebergsa...",da,0.975193
1,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Hovedretter,En halv grillkylling,,108.0,[],en,0.000000
2,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Maxi Cheeseburger,"briochebolle med fyld af ca. 300 grams oksebøf, ost, sal...",128.0,"[briochebolle, fyld, cirka, 300, gram, oksebøf, ost, sal...",da,0.988594
3,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Gorgonzola,"tomatsauce, ost, gorgonzola, champignon, løg og rucola.",115.0,"[tomatsauce, ost, gorgonzola, champignon, løg, rucola]",da,0.982142
4,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Caprese,"tomatsauce, ost, kødstrimler, paprika og bearnaisesauce.",115.0,"[tomatsauce, ost, kødstrimler, paprika, bearnaisesauce]",da,1.000000
...,...,...,...,...,...,...,...,...,...
9962,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Quesadillas,Mini Corn Quesadilla,"corn tortilla, ost, carnitas pork eller kylling, salsa m...",65.0,"[corn, tortilla, ost, carnitas, pork, kylling, salsa, ma...",en,1.000000
9963,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Burritos,Burrito - Block Party BBQ 🌶️,"hvede tortilla, ris, raw slaw, sorte bønner, dit valg af...",145.0,"[hvede, tortilla, ris, raw, slaw, sort, bønn, din, valg,...",en,1.000000
9964,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Børnemenu,Kids Bowl,"ris, romaine, barbacoa beef/grillet kylling/veggie strip...",89.0,"[ris, romaine, barbacoa, beef, grillet, kylling, veggie,...",en,1.000000
9965,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Dips,BBQ Sauce,.,10.0,[],en,1.000000
9966,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Sodavand,Faxe Kondi 33cl,.,35.0,[],en,1.000000

In [13]:
for d in items_raw.lemmas:
    print(d)

['sesambolle', 'fyld', 'oksebøf', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
[]
['briochebolle', 'fyld', 'cirka', '300', 'gram', 'oksebøf', 'ost', 'salat', 'tomat', 'løg', 'agurk']
['tomatsauce', 'ost', 'gorgonzola', 'champignon', 'løg', 'rucola']
['tomatsauce', 'ost', 'kødstrimler', 'paprika', 'bearnaisesauce']
['tomatsauce', 'ost', 'kylling', 'pepperoni', 'paprika']
['tomatsauce', 'ost', 'spinat', 'oliven', 'gorgonzola', 'champignon', 'hvidløg']
['pommes', 'frites', 'salat', 'remoulade']
['tomatsauce', 'ost', 'kebab', 'kylling', 'pepperoni', 'kalkunskinke', 'salat', 'dressing']
['oksekødsret', 'pommes', 'frites', 'hummus', 'salat', 'brød']
[]
['tyrkisk', 'brød', 'fyld', 'valgfri', 'protein', 'salat', 'tomat', 'agurk', 'creme', 'fraiche']
['box', 'fyld', 'kebab', 'salat', 'pommes', 'frites', 'dressing']
['tomatsauce', 'ost', 'kalkunskinke']
['pommes', 'frites', 'salat', 'dressing', 'remoulade']
[]
['tomatsauce', 'ost', 'kebab', 'champignon']
['græsk', 'bøf', 'løg', 'pommes', 'frites', 'jalapeños', 'salat', 'bearnaisesauce']
['tomatsauce', 'ost', 'rej', 'tun', 'paprika', 'løg']
['tomatsauce', 'ost', 'oksekød', 'paprika', 'cocktailpøls']
['falafel', 'ret', 'pommes', 'frites', 'hummus', 'salat', 'brød']
['tomatsauce', 'ost', 'shawarma', 'pepperoni', 'jalapeños']
['pommes', 'frites', 'salat', 'dressing', 'bearnaisesauce']
[]
[]
['tomatsauce', 'ost', 'kødstrimler', 'champignon', 'løg']
['pommes', 'frites', 'hummus', 'salat', 'brød']
['briochebolle', 'fyld', 'cirka', '300', 'grams', 'oksebøf', 'bacon', 'ost', 'salat', 'tomat', 'løg', 'agurk', 'thousand', 'island', 'dressing']
['tomatsauce', 'ost', 'lammekød', 'champignon', 'jalapeños', 'pesto', 'paprika']
['pommes', 'frites', 'hummus', 'salat', 'brød']
[]
['tomatsauce', 'ost', 'kylling', 'pesto', 'tomat', 'rucola']
['tomatsauce', 'ost', 'kylling', 'kalvebacon', 'ananas', 'paprika']
['tomatsauce', 'ost', 'pepperoni', 'gorgonzola', 'hvidløg']
['tomatsauce', 'ost', 'ananas', 'kalkunskinke']
['tomatsauce', 'ost', 'shawarma', 'kalvebacon', 'champignon']
['tomatsauce', 'ost', 'oksekød', 'chili', 'pepperoni', 'løg', 'jalapeños']
['tomatsauce', 'ost', 'kødstrimler', 'champignon', 'paprika', 'oliven']
['briochebolle', 'fyld', 'falafel', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['sesambolle', 'fyld', 'oksebøf', 'kalvebacon', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
['almindelig', 'burger', 'pommes', 'frites', 'valgfri', '0,33', 'l', 'sodavand']
['tomatsauce', 'ost', 'champignon', 'paprika', 'løg', 'ananas', 'artiskok']
[]
['briochebolle', 'fyld', 'cirka', '300', 'gram', 'oksebøf', 'salat', 'tomat', 'løg', 'agurk']
['sesambolle', 'fyld', 'oksebøf', 'jalapeños', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
[]
['briochebolle', 'fyld', 'vegetarisk', 'bøf', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['fladbrød', 'fyld', 'valgfri', 'protein', 'salat', 'tomat', 'løg', 'dressing']
['græsk', 'salat', 'fetaost', 'oliven', 'brød']
['tomatsauce', 'ost', 'pepperoni', 'kalvebacon', 'kalkunskinke', 'æg']
['briochebolle', 'fyld', 'oksebøf', 'kalvebacon', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['briochebolle', 'fyld', 'oksebøf', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['halv', 'kylling', 'pommes', 'frites', 'salat', 'jalapeños', 'valgfri', 'dyppelse']
['tomatsauce', 'ost', 'falafel', 'tomat', 'oliven', 'gorgonzola', 'rucola']
['tomatsauce', 'ost', 'kalkunskinke', 'shawarma', 'paprika', 'hvidløg']
[]
['bøf', 'løg', 'champignon', 'pommes', 'frites', 'salat', 'bearnaisesauce']
['tomatsauce', 'ost', 'pepperoni']
['tomatsauce', 'ost', 'oksekød', 'pepperoni', 'champignon']
['tomatsauce', 'ost', 'kødsauce', 'løg']
['tomatsauce', 'ost', 'kalkunskinke', 'champignon']
['tomatsauce', 'ost', 'cocktailpøls', 'pepperoni', 'champignon']
[]
[]
['tomatsauce', 'ost', 'valgfri', 'protein']
['sesambolle', 'fyld', 'oksebøf', 'ost', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
['briochebolle', 'fyld', '2x', 'oksebøf', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['tomatsauce', 'ost']
['tomatsauce', 'ost', 'pepperoni', 'kødstrimle', 'gorgonzola']
['sandwich', 'fyld', 'valgfri', 'protein', 'ost', 'salat', 'tomat', 'løg', 'valgfri', 'dressing']
['tomatsauce', 'ost', 'kalkunskinke']
['tomatsauce', 'ost', 'kødsauce', 'spaghetti']
['tomatsauce', 'ost', 'kalkunskinke', 'kalvebacon', 'løg', 'æg']
['pommes', 'frites', 'valgfri', '0,33', 'l', 'sodavand']
['hjemmelavet', 'pitabrød', 'fyld', 'valgfri', 'protein', 'salat', 'tomat', 'løg', 'valgfri', 'dressing']
['tomatsauce', 'ost', 'gorgonzola', 'løg', 'artiskok', 'oliven', 'rucola']
['tomatsauce', 'ost', 'kødsauce', 'jalapeños', 'pepperoni', 'chili']
['briochebolle', 'fyld', 'kyllingebøf', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['briochebolle', 'fyld', 'cirka', '300', 'grams', 'oksebøf', 'oksebacon', 'salat', 'tomat', 'løg', 'agurk']
[]
['briochebolle', 'fyld', 'oksebøf', 'ost', ' ', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['hønsesalat', 'grøn', 'crudité', 'asparges', 'sprød', 'kyllingeskind', 'karse', 'gram', '+', 'l', '+', 'æg', '+', 'selleri', '+', 'sennep']
['økologisk', 'myntebrus', 'naturfrisk', '25cl']
['gulerødd', 'knoldselleri', 'blomkål', 'eddike', 'sukker', 'mayonnaise', 'rapsolie', 'æg', 'dijonsennep', 'æbleeddike', 'salt', 'peber', 'løg', 'chili', 'sennep', 'gurkemeje', 'paprika', 'maizena']
['5,5', '0,33', 'l']
['rødbede', 'eddike', 'anis', 'sennepsfrø', 'sukker', 'kanel', 'allehåned', 'peber']
['Riesling', '11,5', '0,75', 'l']
['avocado', 'citronemulsion', 'kål', 'salatløg', 'rugchips', 'gram', '+', 'l', '+', 'æg']
['kartoffel', 'sæson', 'emulsion', 'grøn', 'løg', 'sprød', 'kartoffel', 'urt', 'g', '+', 'l', '+', 'æg', '+', 'sennep']
[]
['pålægschokolademad', 'mørk', 'chokolade', 'friis-holm', 'flødekaramel', 'blåbærkompot', 'vaniljecreme', 'mandle', 'gram', '+', 'l', '+', 'æg', '+', 'nødder']
['3', 'stk.', 'smørrebrød', 'avocado', 'hønsesalat', 'roastbeef']
['3', 'stk.', 'smørrebrød', 'kartoffel', 'gul', 'bede', 'avocado']
['svampetoast', 'svamp', 'funga', 'Farm', 'Marsala', 'æbl', 'creme', 'fraiche', 'citronskal', 'persille', 'g', '+', 'l', '+', 'sennep']
['cremet', 'æggesalat', 'cornichon', 'bladselleri', 'purløg']
['dronning', 'victoria-ost', 'Nørup', 'mejeri', 'sæson', 'kompot', 'mandle', 'kørvel', 'g', '+', 'l', '+', 'nødder']
['14,5', ' ', '37,50', 'cl']
['gammeldags', 'sild', 'karrysalat', 'forårsløg', 'æbl', 'boghvedekerne', 'g', '+', 'l', '+', 'æg']
['varmrøget', 'laks', 'laks', 'cremefraiche', 'past', 'æggeblomme', 'olie', 'capers', 'dild', 'citron']
['skinke', 'ost', 'agurk', 'skalotteløgsrelish', 'hjertesalat', 'sennepscreme']
[]
['angelis', 'rosso', 'piceno', ' ', '14,5', ' ', '0,75', 'l']
['cremet', 'hønsesalat', 'bacon', 'æbl', 'drueagurke', 'selleri']
['herslev', '0,3', '0,33l']
['oksetatar', 'sæson', 'emulsion', 'grøn', 'forårsløg', 'sprød', 'kartoffel', 'karse', 'gram', '+', 'l', '+', 'æg', '+', 'sennep']
['frikadell', 'kalv', 'flæsk', 'kartoffelsalat', 'radis', 'urt']
['smørstegt', 'rødspætte', 'rejesalat', 'selleri', 'salatløg', 'paprika', 'dild', 'gram', '+', 'l', '+', 'æg', '+', 'selleri']
['agurke', 'hvidvinseddike', 'sukker', 'vand']
['økologisk', 'æblemost', 'naturfrisk', '27,50cl']
['mandelkage', 'citrussirup', 'blå', 'birkes', 'vaniljecreme', 'mandle', 'g', '+', 'l', '+', 'æg', '+', 'nødder']
['hønsesalat', 'smørristet', 'surdejsbrød', 'rødløg', 'baconcrumble', 'urt', 'gram', '+', 'l', '+', 'æg', '+', 'sennep']
['4', 'stk.', 'smørrebrød', 'kartoffel', 'rødspætte', 'hønsesalat', 'trifli']
['agurk', 'avocado', 'friskost', 'jalapeño', 'tomat', 'myntecreme', 'mandle']
['aamanns', 'herslev', '5', '0,33l']
['sild', 'sukker', 'eddike', 'løg', 'allehåned', '3', 'stor', 'filet']
['5,0', '0,33', 'l']
['laksetatar', 'æbl', 'fennikel', 'rugkrumme', 'dild', 'g', '+', 'l', '+', 'æg', '+', 'sennep']
[]
['gul', 'bede', 'estragonemulsion', 'forårsløg', 'glaskål', 'salatløg', 'boghvedekerne', 'gram', '+', 'l', '+', 'æg', '+', 'sennep']
['trifli', 'sæson', 'bær', 'frugtkompot', 'mascarponecreme', 'polynesisk', 'vanilje', 'mandelcrumble', 'l', '+', 'nødder']
['koldrøget', 'laks', 'hiddenfjord', 'friskost', 'agurk', 'olivenolie', 'mandle']
['panere', 'smørstegt', 'rødspætte', 'rodfrugtremoulade', 'rødløg', 'urt', 'gram', '+', 'l', '+', 'æg', '+', 'selleri']
['roastbeef', 'bearnaisecreme', 'let', 'tomat', 'agurke', 'sprød', 'kartoffel', 'gram', '+', 'l', '+', 'æg']
['håndpillet', 'rej', 'smørristet', 'surdejsbrød', 'tomatmayonnaise', 'salatløg', 'tomatpulver', 'urt', 'g', '+', 'l', '+', 'æg']
['høns', 'citron', 'sennep', 'gulerødd', 'selleri']
['roastbeef', 'bearnaise', 'agurke', 'sprød', 'kartoffel']
['æg', 'reje', 'tomatemulsion', 'cherrytomat', 'bladselleri', 'mandle', 'gram', '+', 'l', '+', 'æg', '+', 'sennep', '+', 'nødder']
['chokolademousse', '60', 'valrhona', 'oriado', 'chokolade', 'kakaonib', 'l', '+', 'æg']
['Riesling', '11,5', '37,50', 'cl']
['rapsolie', 'æg', 'dijonsennep', 'æbleeddike', 'salt', 'peber']
[]
['sprød', 'chips', 'kikærtemel', 'trio', 'livlig', 'syrlig', 'chutney']
['suppe', 'linse', 'kylling', 'tomat', 'vegetar']
['sprød', 'samosa', 'kartoffel', 'ært', 'lækre', 'syrlig', 'kikært', 'tomat', 'løg', 'yoghurt', 'tamarind', 'mynte', 'chutney', 'drys', 'chat', 'massala']
['moset', 'kartoffel', 'frisk', 'grøn', 'ærter', 'strejf', 'chilli', 'aromatisk', 'løg', 'blanding', 'karrykrydderi', 'velsmagende', 'bøff', 'pande']
['hjemmelavet', 'panee', 'grøntsag', 'urt', 'frituresteg', 'kikærtemel', 'yoghurt']
['grøntsag', 'varm', 'traditionel', 'orientalsk', 'krydderi', 'sprøed', 'tekstur', 'gylden', 'farve']
['saftig', 'mør', 'lammekotelet', 'blanding', 'yoghurt', 'krydderi', 'krydderurt', 'kød', 'let', 'forkullet', 'smag']
['frisk', 'paneer', 'yoghurt', 'tomat', 'løg', 'peberfrugt']
['sprødstegt', 'fisk', 'syrlig', 'citron', 'aromatisk', 'varm', 'krydderi']
['mør', 'tandoori', 'lammekød', 'aromatisk', 'kashmiri', 'krydderi', 'yoghurt', 'løg', 'tomat']
['kylling', 'blanding', '   ', 'aromatisk', 'krudderi', 'karamelliseret', 'løg', 'saftig', 'tomat']
['oksekød', 'kebab', 'punjabi', 'krydderi', 'ingefær', 'hvidløg', 'lime', 'frisk', 'koriande']
['butter', 'chicken', 'ris', 'salat', 'pommes', 'frites']
['saftig', 'lammekød', 'robust', 'ingefær', 'løg', 'rig', 'tomatsovs', '\n\n', 'ris', 'naanbrød', 'separat']
['lammekød', 'punjabikrydderi', 'lækker', 'cremet', 'tomatsovs', '\n\n', 'ris', 'naanbrød', 'separat']
['tandoori', 'lammekød', 'blanding', ' ', 'krydderi', 'cremet', 'fløde', 'smørsovs', 'langtidskogt', 'perfektion', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'lammekød', 'lækker', 'cremet', 'cashewsovs', 'varm', 'aroma', 'garam', 'massala', 'rig', 'smag', 'frisk', 'fløde', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'lammekød', 'mild', 'karry', 'finthakket', 'spinat', 'aromatisk', 'urt', 'ret', 'lammets', 'fyldig', 'smag', 'mild', 'rig', 'smag', 'spinat', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'lammekød', 'blanding', 'sagte', 'løg', 'aromatisk', 'urt', 'saftig', 'okra', 'lammets', 'rig', 'fyldig', 'smag', 'perfekt', 'subtil', 'sød', 'smag', 'okra', '\n\n', 'ris', 'naanbrød', 'separat']
['delikat', 'oksekød', 'syrlig', 'karry', 'traditionel', 'krydderi', 'frisk', 'hvidløg', 'ingefær', 'tomat', 'skrap', 'kontrast', '\n\n', 'ris', 'naanbrød', 'separat']
['mør', 'oksekød', 'velkrydret', 'kashmiri', 'karry', 'kartoffel', 'rig', 'sovs', 'fyldig', 'tilfredstillende', 'element', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'oksekød', 'lækker', 'karry', 'blanding', 'aromatisk', 'urt', 'velsmagende', 'krydderi', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'kylling', 'aromatisk', 'ingefær', 'sprød', 'peberfrugt', 'æg', 'simmer', 'livlig', 'velsmagende', 'sovs', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'tandoori', 'kylling', 'mildt', 'rig', 'cremet', 'velsmagende', 'smørsovs', 'strejf', 'sødme', '\n\n', 'ris', 'naanbrød', 'separat']
['kylling', 'tyk', 'cremet', 'kokos', 'karrysovs', 'urt', 'velsmagende', 'ret', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'kylling', 'mild', 'karry', 'håndhakket', 'krydderi', 'rig', 'velsmagende', 'ret', '\n\n', 'ris', 'naanbrød', 'separat']
['kylling', 'krydre', 'cremet', 'karrysovs', 'aromatisk', 'krydderi', 'appetitvækkende', 'rig', 'smag', '\n\n', 'ris', 'naanbrød', 'separat']
['kongereje', 'chili', 'lime', 'rig', 'cremet', 'sovs', 'smør', 'fløde', 'kokosmælk', 'velsmagende', 'krydderi', 'luksuriøs', 'skaldyrsmag', '\n\n', 'ris', 'naanbrød', 'separat']
['tandoori', 'kongereje', 'eddike', 'citron', 'ingefær', 'hvidløg', 'rig', 'smagfuld', 'zesty', 'ret', '\n', 'ris', 'naanbrød', 'separat']
['kongereje', 'rig', 'puré', 'hvidløg', 'ingefær', 'tomat', 'løg', 'cremet', 'karrysauce', '\n\n', 'ris', 'naanbrød', 'separat']
['saftig', 'kongereje', 'tyk', 'sovs', 'saftig', 'tomat', 'ingefær', 'hvidløg', 'velsmagende', 'løg', '\n\n', 'ris', 'naanbrød', 'separat']
['urteinfuseret', 'vegetablisk', 'kofta', 'frisk', 'pane', 'mild', 'cremet', 'karrysovs', 'skrape', 'aromatisk', 'krydderi', '\n\n', 'ris', 'naanbrød', 'separat']
['frisk', 'ærter', 'smøragtigt', 'hjemmelavet', 'panee', 'robust', 'velsmagende', 'ret', '\n\n', 'ris', 'naanbrød', 'separat']
['hjemmelavet', 'panee', 'frisk', 'urt', ' ', 'skrap', 'orientalsk', 'krydderi', 'delikat', 'cremet', 'sauce', 'let', 'luftig', 'tekstur', '\n\n', 'ris', 'naanbrød', 'separat']
['kikærte', 'stærk', 'aromatisk', 'punjabi', 'krydderi', 'frisk', 'koriande', 'strejf', 'citron', 'ekstra', 'dimension', 'smag', '\n\n', 'ris', 'naanbrød', 'separat']
['frisk', 'blomkål', 'mør', 'kartoffel', 'tomatpuré', 'aromatisk', 'ingefær', 'spidskomme', 'sagtig', 'robust', 'smag', '\n\n', 'ris', 'naanbrød', 'separat']
['pandesteget', 'linse', 'frisk', 'aromatisk', 'hvidløg', 'ingefær', 'blanding', 'krydderi', 'rig', 'skrap', 'smag', '\n\n', 'ris', 'naanbrød', 'separat']
['okra', 'syrlig', 'blanding', 'spidskomme', 'lime', 'løg', 'sød', 'tomat', 'smagfuld', 'zesty', 'ret', '\n\n', 'ris', 'naanbrød', 'separat']
['yoghurt', 'salt', 'sukker']
[]
['lam']
['risret', 'reje']
['risret', 'grøntsag']
['kylling']
['lam']
['1', 'x', 'paneer', 'tikka', '\n', '1', 'x', 'Raita', 'chutney', '\n', '1', 'x', 'lamb', 'spinach', '\n', '1', 'x', 'chicken', 'achari', '\n', '1', 'x', 'barbari', 'dal', 'tarka', '\n', '1', 'x', 'Pilau', 'rice', '\n', '1', 'x', 'tandoori', 'Garlic', 'naan']
['1', 'x', 'Samosa', '\n', '1', 'x', 'Raita', 'chutney', '\n', '1', 'x', 'nargisi', 'Beef', 'Bhuna', '\n', '1', 'x', 'chicken', 'handi', '\n', '1', 'x', 'malai', 'kofta', '\n', '1', 'x', 'plain', 'rice', '\n', '1', 'x', 'tandoori', 'naan']
['1', 'x', 'onion', 'bhaji', '\n', '1', 'x', 'Raita', 'chutney', '\n', '1', 'x', 'butter', 'Chicken', '\n', '1', 'x', 'lamb', 'rogan', 'josh', '\n', '1', 'x', 'aloo', 'Gobi', '\n', '1', 'x', 'Pilau', 'rice', '\n', '1', 'x', 'tandoori', 'Garlic', 'naan']
['1', 'x', 'aloo', 'tikki', '\n', '1', 'x', 'Raita', 'chutney', '\n', '1', 'x', 'punjabi', 'bhindi', 'massala', '\n', '1', 'x', 'lahori', 'channa', 'massala', '\n', '1', 'x', 'Paneer', 'makhani', '\n', '1', 'x', 'vegetable', 'rice', '\n', '1', 'x', 'tandoori', 'naan']
['1', 'x', 'aloo', 'tikki', '\n', '1', 'x', 'Raita', 'chutney', '\n', '1', 'x', 'punjabi', 'bhindi', 'massala', '\n', '1', 'x', 'lahori', 'channa', 'massala', '\n', '1', 'x', 'Paneer', 'makhani', '\n', '1', 'x', 'vegetable', 'rice', '\n', '1', 'x', 'tandoori', 'naan']
['1', 'x', 'tandoori', 'lamb', 'tikka', '\n', '1', 'x', 'chicken', 'balti', '\n', '1', 'x', 'nawabi', 'malai', 'king', 'Prawn', '\n', '1', 'x', 'Palak', 'paneer', '\n', '1', 'x', 'Pilau', 'ris', '\n', '1', 'x', 'tandoori', 'naan', '\n', '1', 'x', 'chutney', '\n', '1', 'x', 'raita']
['1', 'x', 'chicken', 'tikka', '\n', '1', 'x', 'lamb', 'tikka', 'massala', '\n', '1', 'x', 'butter', 'chicken', '\n', '1', 'x', 'Shahjahani', 'Paneer', 'tikka', 'massala', '\n', '1', 'x', 'vegetable', 'ris', '\n', '1', 'x', 'tandoori', 'garlic', 'naan', '\n', '1', 'x', 'chutney', '\n', '1', 'x', 'raita']
['1', 'x', 'al-diwan', 'mixed', 'grill', '\n', '1', 'x', 'king', 'Prawn', 'tandoori', '\n', '1', 'x', 'sultani', 'lamb', 'butter', 'tikka', '\n', '1', 'x', 'chicken', 'tikka', 'masala', '\n', '1', 'x', 'Paneer', 'jalfrezi', '\n', '1', 'x', 'hydrabadi', 'vegetable', 'Biryani', '\n', '1', 'x', 'tandoori', 'naan', '\n', '1', 'x', 'chutney', '\n', '1', 'x', 'raita']
['indisk', 'lager', 'øl']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['langkornet', 'basmatiris']
['langkornet', 'basmatiris', 'ærter', 'krydderi']
['langkornet', 'basmatiris', 'udvalgte', 'grøntsag']
['youghurt', 'salat', 'forskellig', 'krydderi']
['hus', 'specialitet']
[]
['bombay', 'ipa', 'classic', 'new', 'york', 'lager', 'king', '´', 's', 'county', 'brown', 'ale']
[]
[]
[]
['valgfri', 'protein', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'hjemmelavet', 'yoghurt', 'dressing', 'pommes', 'frites', 'mayo', 'gazoz', '0,33', 'l.']
['valgfri', 'protein', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'hjemmelavet', 'yoghurt', 'dressing', 'pommes', 'frites', 'mayo', 'gazoz', '0,33', 'l.']
['valgfri', 'protein', 'pommes', 'frites', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'hjemmelavet', 'yoghurt', 'dressing', 'mayo', 'gazoz', '0,33', 'l.']
[]
[]
['valgfri', 'protein', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'hjemmelavet', 'yoghurt', 'dressing']
['valgfri', 'protein', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'hjemmelavet', 'yoghurt', 'dressing']
['valgfri', 'protein', 'pommes', 'frites', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'hjemmelavet', 'yoghurt', 'dressing']
['nudelsalat', 'oksekod', 'forårsrulle', 'grontsage', 'urt', 'log', 'fiskesauce']
['3', 'x', 'forårsrulle', 'gris', 'glasnudle', 'grøntsag', 'salat', 'mynte', 'fiskesauce']
['3', 'x', 'kylling', 'grøntsag', 'soja', 'sauce']
['2', 'x', ' ', 'frisk', 'rulle', 'tigerreje', 'risnudel', 'koriande', 'mynte', 'hoisin-peanuts', 'sauce']
['4', 'x', 'wontons', 'grontsage', 'soja', '.sauce']
['4', 'wontons', '4', 'frisk', 'rulle', '4', 'vietnamesisk', 'rulle', '4', 'samosa', '\n', 'sauce', 'soja', 'hoisin-peanuts', 'sauce']
['spicy', 'oksekød', ' ', 'risnudel', 'sprød', 'grøntsag', 'urt', 'peanut', 'løg', 'fiskesauce']
['risnudel', 'sprød', 'grøntsag', 'urt', 'peanut', 'løg', 'fiske', 'sauce', 'vietnamesiskerulle']
['risnudel', 'sprød', 'grøntsag', 'urt', 'peanut', 'løg', 'fiskesauce', 'citrongræs-gris']
['citrongres-gris', 'ris', 'agurk', 'frisk', 'spidskål', 'urt', 'gulerodspickles']
['spicy', 'oksekødssalat', 'sprød', 'salat', 'urt', 'ris']
['karrykylling', 'gulerødd', 'bønnespir', 'forårsløg', 'ris']
['nudelsalat', 'vegetarisk', 'wontons', 'risnudel', ' ', 'sprode', 'grontsage', 'urt', 'peanuts', 'sojasauce']
[]
[]
[]
['pommes', 'frites', 'valgfri', 'protein']
['hjemmelavet', 'durum', 'm.', 'valgfri', 'protein', 'pommes', 'frites', 'valgfri', 'sodavand']
['chili', 'cheese', 'tops', 'mayo']
['mozzarella', 'sticks', 'mayo']
['onion', 'rings', 'mayo']
['mayo']
['hummus', 'tzatziki']
['kebab', 'ret', 'pomes', 'frites', 'salat', 'dressing', 'tzatziki', 'hummus']
['kylling', 'ret', 'pommes', 'frites', 'salat', 'dressing', 'tzatziki', 'hummus']
['falafel', 'ret', 'pommes', 'frites', 'salat', 'dressing', 'tzatziki', 'hummus']
['börek', 'ost', 'spinat']
[]
[]
[]
[]
[]
[]
[]
[]
[]
['hjemmelavet', 'pita', 'm.', 'valgfri', 'protein', 'pommes', 'frites', 'valgfri', 'sodavand']
['bowl', 'pommes', 'frites', 'valgfri', 'protein', 'valgfri', 'dressing', 'tzatziki', 'hummus']
['hjemmelavet', 'durum', 'm.', 'valgfri', 'protein']
[]
[]
['hjemmelavet', 'pita', 'm.', 'valgfri', 'protein']
[]
[]
[]
['brød', 'smør']
['grøn', 'salat', 'ærter', 'tomat', 'gulerødd', 'oliven', 'dressing']
['valgfri', 'dip']
['mozzarella', 'løg', 'valgfri', 'dip']
['valgfri', 'dip']
['pepperoni', 'oksekød', 'skinke', 'champignon', 'løg', 'rød', 'peber']
['pepperoni', 'oksekød', 'skinke', 'champignon', 'løg', 'rød', 'peber']
['reje', 'tun', 'champignon']
['reje', 'tun', 'champignon']
['skinke', 'champignon']
['skinke', 'champignon']

In [9]:
items_raw

,wolt_id,venue,category,item,description,price_dkk,lemmas
0,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Klassisk okseburger,"sesambolle med fyld af oksebøf, dressing, ketchup, icebe...",88.0,"[sesambolle, fyld, oksebøf, dressing, ketchup, icebergsa..."
1,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Hovedretter,En halv grillkylling,,108.0,[]
2,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Burger,Maxi Cheeseburger,"briochebolle med fyld af ca. 300 grams oksebøf, ost, sal...",128.0,"[briochebolle, fyld, cirka, 300, gram, oksebøf, ost, sal..."
3,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Gorgonzola,"tomatsauce, ost, gorgonzola, champignon, løg og rucola.",115.0,"[tomatsauce, ost, gorgonzola, champignon, løg, rucola]"
4,6a71e83b2c4b0028d09cf99e,1001 Nat Pizza,Pizzaer,Caprese,"tomatsauce, ost, kødstrimler, paprika og bearnaisesauce.",115.0,"[tomatsauce, ost, kødstrimler, paprika, bearnaisesauce]"
...,...,...,...,...,...,...,...
9962,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Quesadillas,Mini Corn Quesadilla,"corn tortilla, ost, carnitas pork eller kylling, salsa m...",65.0,"[corn, tortilla, ost, carnitas, pork, kylling, salsa, ma..."
9963,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Burritos,Burrito - Block Party BBQ 🌶️,"hvede tortilla, ris, raw slaw, sorte bønner, dit valg af...",145.0,"[hvede, tortilla, ris, raw, slaw, sort, bønn, din, valg,..."
9964,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Børnemenu,Kids Bowl,"ris, romaine, barbacoa beef/grillet kylling/veggie strip...",89.0,"[ris, romaine, barbacoa, beef, grillet, kylling, veggie,..."
9965,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Dips,BBQ Sauce,.,10.0,[]
9966,5c7796f8e50c02000bbc7523,Zócalo Tivoli Food Hall,Sodavand,Faxe Kondi 33cl,.,35.0,[]

In [17]:
import json

with open(WOLT_DATA_DIR / AREA / "description_ingredients.json") as f:
    desc_to_ingr = json.load(f)

items_raw["ingredients"] = items_raw.description.map(lambda d: desc_to_ingr.get(d, []))
for i in items_raw.ingredients:
    print(i)

['sesambolle', 'oksekød', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
[]
['briochebolle', 'oksekød', 'ost', 'salat', 'tomat', 'løg', 'agurk']
['tomatsauce', 'ost', 'gorgonzola', 'champignon', 'løg', 'rucola']
['tomatsauce', 'ost', 'kødstrimler', 'peberfrugt', 'bearnaise']
['tomatsauce', 'ost', 'kylling', 'pepperoni', 'peberfrugt']
['tomatsauce', 'ost', 'spinat', 'oliven', 'gorgonzola', 'champignon', 'hvidløg']
['pommes frites', 'salat', 'remoulade']
['tomatsauce', 'ost', 'kebab', 'kylling', 'pepperoni', 'kalkunskinke', 'salat', 'dressing']
['oksekød', 'pommes frites', 'hummus', 'salat', 'brød']
[]
['tyrkisk brød', 'salat', 'tomat', 'agurk', 'creme fraiche']
['kebab', 'salat', 'pommes frites', 'dressing']
['tomatsauce', 'ost', 'kalkunskinke']
['pommes frites', 'salat', 'dressing', 'remoulade']
[]
['tomatsauce', 'ost', 'kebab', 'champignon']
['oksekød', 'løg', 'pommes frites', 'jalapeño', 'salat', 'bearnaise']
['tomatsauce', 'ost', 'reje', 'tun', 'peberfrugt', 'løg']
['tomatsauce', 'ost', 'oksekød', 'peberfrugt', 'cocktailpølse']
['falafel', 'pommes frites', 'hummus', 'salat', 'brød']
['tomatsauce', 'ost', 'shawarma', 'pepperoni', 'jalapeño']
['pommes frites', 'salat', 'dressing', 'bearnaise']
[]
[]
['tomatsauce', 'ost', 'kødstrimler', 'champignon', 'løg']
['pommes frites', 'hummus', 'salat', 'brød']
['briochebolle', 'oksekød', 'bacon', 'ost', 'salat', 'tomat', 'løg', 'agurk', 'thousand island dressing']
['tomatsauce', 'ost', 'lammekød', 'champignon', 'jalapeño', 'pesto', 'peberfrugt']
['pommes frites', 'hummus', 'salat', 'brød']
[]
['tomatsauce', 'ost', 'kylling', 'pesto', 'tomat', 'rucola']
['tomatsauce', 'ost', 'kylling', 'kalvebacon', 'ananas', 'peberfrugt']
['tomatsauce', 'ost', 'pepperoni', 'gorgonzola', 'hvidløg']
['tomatsauce', 'ost', 'ananas', 'kalkunskinke']
['tomatsauce', 'ost', 'shawarma', 'kalvebacon', 'champignon']
['tomatsauce', 'ost', 'oksekød', 'chili', 'pepperoni', 'løg', 'jalapeño']
['tomatsauce', 'ost', 'kødstrimler', 'champignon', 'peberfrugt', 'oliven']
['briochebolle', 'falafel', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['sesambolle', 'oksekød', 'kalvebacon', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
['burger', 'pommes frites', 'sodavand']
['tomatsauce', 'ost', 'champignon', 'peberfrugt', 'løg', 'ananas', 'artiskok']
[]
['briochebolle', 'oksekød', 'salat', 'tomat', 'løg', 'agurk']
['sesambolle', 'oksekød', 'jalapeño', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
[]
['briochebolle', 'vegetarbøf', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['fladbrød', 'salat', 'tomat', 'løg', 'dressing']
['græsk salat', 'feta', 'oliven', 'brød']
['tomatsauce', 'ost', 'pepperoni', 'kalvebacon', 'kalkunskinke', 'æg']
['briochebolle', 'oksekød', 'kalvebacon', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['briochebolle', 'oksekød', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['kylling', 'pommes frites', 'salat', 'jalapeño', 'dip']
['tomatsauce', 'ost', 'falafel', 'soltørret tomat', 'oliven', 'gorgonzola', 'rucola']
['tomatsauce', 'ost', 'kalkunskinke', 'shawarma', 'peberfrugt', 'hvidløg']
[]
['oksekød', 'løg', 'champignon', 'pommes frites', 'salat', 'bearnaise']
['tomatsauce', 'ost', 'pepperoni']
['tomatsauce', 'ost', 'oksekød', 'pepperoni', 'champignon']
['tomatsauce', 'ost', 'kødsauce', 'løg']
['tomatsauce', 'ost', 'kalkunskinke', 'champignon']
['tomatsauce', 'ost', 'cocktailpølse', 'pepperoni', 'champignon']
[]
[]
['tomatsauce', 'ost']
['sesambolle', 'oksekød', 'ost', 'dressing', 'ketchup', 'icebergsalat', 'løgring', 'tomat', 'agurk']
['briochebolle', 'oksekød', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['tomatsauce', 'ost']
['tomatsauce', 'ost', 'pepperoni', 'kødstrimler', 'gorgonzola']
['sandwich', 'ost', 'salat', 'tomat', 'løg', 'dressing']
['tomatsauce', 'ost', 'kalkunskinke']
['tomatsauce', 'ost', 'kødsauce', 'spaghetti']
['tomatsauce', 'ost', 'kalkunskinke', 'kalvebacon', 'løg', 'æg']
['pommes frites', 'sodavand']
['pitabrød', 'salat', 'tomat', 'løg', 'dressing']
['tomatsauce', 'ost', 'gorgonzola', 'løg', 'artiskok', 'oliven', 'rucola']
['tomatsauce', 'ost', 'kødsauce', 'jalapeño', 'pepperoni', 'chili']
['briochebolle', 'kylling', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['briochebolle', 'oksekød', 'oksebacon', 'salat', 'tomat', 'løg', 'agurk']
[]
['briochebolle', 'oksekød', 'ost', 'tomat', 'agurk', 'mayonnaise', 'ketchup', 'salat']
['hønsesalat', 'grøntsag', 'asparges', 'kyllingeskind', 'karse']
['sodavand', 'mynte']
['gulerod', 'knoldselleri', 'blomkål', 'eddike', 'sukker', 'mayonnaise', 'løg', 'chili', 'sennep', 'gurkemeje', 'paprika']
['øl']
['rødbede', 'eddike', 'anis', 'sennepsfrø', 'sukker', 'kanel', 'allehånde', 'peber']
['hvidvin']
['avocado', 'citron', 'kål', 'syltede rødløg', 'rugbrødschips']
['kartoffel', 'grøntsag', 'syltede løg', 'krydderurt']
[]
['chokolade', 'karamel', 'blåbærkompot', 'vaniljecreme', 'mandel', 'rugbrød']
['avocado', 'hønsesalat', 'roastbeef', 'smørrebrød']
['kartoffel', 'gulerod', 'avocado', 'smørrebrød']
['toastbrød', 'svamp', 'marsala', 'æble', 'creme fraiche', 'citronskal', 'persille']
['æggesalat', 'cornichon', 'bladselleri', 'purløg']
['ost', 'kompot', 'mandel', 'kørvel']
[]
['sild', 'karrysalat', 'forårsløg', 'æble', 'boghvede']
['røget laks', 'laks', 'creme fraiche', 'æggeblomme', 'olie', 'kapers', 'dild', 'citron']
['skinke', 'ost', 'agurk', 'skalotteløg', 'relish', 'hjertesalat', 'sennepscreme']
[]
['rødvin']
['hønsesalat', 'bacon', 'æble', 'drueagurk', 'selleri']
['alkoholfri øl']
['oksetatar', 'grøntsag', 'forårsløg', 'kartoffel', 'karse']
['frikadelle', 'kalvekød', 'svinekød', 'kartoffelsalat', 'radise', 'krydderurt']
['rødspætte', 'rejesalat', 'selleri', 'syltede løg', 'røget paprika', 'dild']
['agurk', 'hvidvinseddike', 'sukker', 'vand']
['æblemost']
['mandelkage', 'citrussirup', 'birkes', 'vaniljecreme', 'mandel']
['hønsesalat', 'surdejsbrød', 'syltede rødløg', 'bacon', 'krydderurt']
['kartoffel', 'rødspætte', 'hønsesalat', 'smørrebrød']
['agurk', 'avocado', 'friskost', 'jalapeño', 'tomat', 'mynte', 'mandel']
['øl']
['sild', 'sukker', 'eddike', 'løg', 'allehånde']
['øl']
['laksetatar', 'laks', 'æble', 'fennikel', 'rugbrødskrummer', 'dild']
[]
['gulbede', 'estragon', 'forårsløg', 'kål', 'syltede rødløg', 'boghvede']
['trifli', 'bær', 'kompot', 'mascarpone', 'vanilje', 'mandel']
['røget laks', 'friskost', 'agurk', 'olivenolie', 'mandel']
['rødspætte', 'remoulade', 'rodfrugt', 'syltede rødløg', 'krydderurt']
['roastbeef', 'bearnaise', 'tomat', 'pickles', 'kartoffel']
['reje', 'surdejsbrød', 'tomatmayonnaise', 'syltede løg', 'tomat', 'krydderurt']
['kylling', 'citron', 'sennep', 'gulerod', 'selleri']
['roastbeef', 'bearnaise', 'pickles', 'kartoffel']
['æg', 'reje', 'tomat', 'cherrytomat', 'bladselleri', 'mandel']
['chokolademousse', 'chokolade', 'kakaonibs']
['hvidvin']
['mayonnaise', 'rapsolie', 'æg', 'dijonsennep', 'æbleeddike', 'salt', 'peber']
[]
['kikærtechips', 'chutney']
['suppe', 'linse', 'kylling', 'tomat', 'grøntsag']
['samosa', 'kartoffel', 'ært', 'kikært', 'tomat', 'løg', 'yoghurt', 'tamarind', 'myntechutney', 'chat masala']
['kartoffel', 'ært', 'chili', 'løg', 'krydderi']
['paneer', 'grøntsag', 'krydderurt', 'kikærtemel', 'yoghurt']
['grøntsag', 'krydderi']
['lammekotelet', 'yoghurt', 'krydderi', 'krydderurt']
['paneer', 'yoghurt', 'krydderi', 'tomat', 'løg', 'peberfrugt']
['fisk', 'citron', 'krydderi']
['lammekød', 'krydderi', 'yoghurt', 'løg', 'tomat']
['kylling', 'krydderi', 'karamelliserede løg', 'tomat']
['kebab', 'oksekød', 'krydderi', 'ingefær', 'hvidløg', 'lime', 'koriander']
['butter chicken', 'kylling', 'ris', 'salat', 'pommes frites']
['lammekød', 'ingefær', 'løg', 'tomatsauce', 'ris', 'naan']
['lammekød', 'krydderi', 'tomatsauce', 'fløde', 'ris', 'naan']
['lammekød', 'krydderi', 'fløde', 'smørsauce', 'ris', 'naan']
['lammekød', 'cashewnød', 'garam masala', 'fløde', 'ris', 'naan']
['lammekød', 'karry', 'spinat', 'krydderurt', 'ris', 'naan']
['lammekød', 'løg', 'krydderurt', 'okra', 'ris', 'naan']
['oksekød', 'karry', 'krydderi', 'hvidløg', 'ingefær', 'tomat']
['oksekød', 'karry', 'kartoffel', 'ris', 'naan']
['oksekød', 'karry', 'krydderurt', 'krydderi', 'ris', 'naan']
['kylling', 'ingefær', 'peberfrugt', 'æg', 'sauce', 'ris', 'naan']
['kylling', 'smørsauce', 'ris', 'naan']
['kylling', 'kokos', 'karrysauce', 'krydderurt', 'ris', 'naan']
['kylling', 'karry', 'krydderi', 'ris', 'naan']
['kylling', 'karrysauce', 'krydderi', 'ris', 'naan']
['kongereje', 'chili', 'lime', 'smør', 'fløde', 'kokosmælk', 'krydderi', 'ris', 'naan']
['kongereje', 'eddike', 'citron', 'ingefær', 'hvidløg', 'ris', 'naan']
['kongereje', 'hvidløg', 'ingefær', 'tomat', 'løg', 'karrysauce', 'ris', 'naan']
['kongereje', 'tomat', 'ingefær', 'hvidløg', 'løg', 'ris', 'naan']
['kofta', 'grøntsag', 'paneer', 'karrysauce', 'krydderi', 'ris', 'naan']
['ært', 'paneer', 'ris', 'naan']
['paneer', 'krydderurt', 'krydderi', 'flødesauce', 'ris', 'naan']
['kikært', 'krydderi', 'koriander', 'citron', 'ris', 'naan']
['blomkål', 'kartoffel', 'tomatpuré', 'ingefær', 'spidskommen', 'ris', 'naan']
['linse', 'hvidløg', 'ingefær', 'krydderi', 'ris', 'naan']
['okra', 'spidskommen', 'lime', 'løg', 'tomat', 'ris', 'naan']
['yoghurt', 'salt', 'sukker']
[]
['ris', 'lammekød']
['ris', 'reje']
['ris', 'grøntsag']
['ris', 'kylling']
['ris', 'lammekød']
['paneer', 'raita', 'chutney', 'lammekød', 'spinat', 'kylling', 'dal', 'pilaf ris', 'naan', 'hvidløg']
['samosa', 'raita', 'chutney', 'oksekød', 'kylling', 'malai kofta', 'ris', 'naan']
['onion bhaji', 'raita', 'chutney', 'butter chicken', 'lammekød', 'kartoffel', 'blomkål', 'pilaf ris', 'naan', 'hvidløg']
['aloo tikki', 'raita', 'chutney', 'okra', 'kikært', 'paneer', 'grøntsag', 'ris', 'naan']
['aloo tikki', 'raita', 'chutney', 'okra', 'kikært', 'paneer', 'grøntsag', 'ris', 'naan']
['lammekød', 'kylling', 'kongereje', 'spinat', 'paneer', 'pilaf ris', 'naan', 'chutney', 'raita']
['kylling', 'lammekød', 'tikka masala', 'butter chicken', 'paneer', 'grøntsag', 'ris', 'naan', 'hvidløg', 'chutney', 'raita']
['grillspyd', 'kongereje', 'lammekød', 'kylling', 'tikka masala', 'paneer', 'grøntsag', 'biryani', 'naan', 'chutney', 'raita']
['øl']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['basmatiris']
['basmatiris', 'ært', 'krydderi']
['basmatiris', 'grøntsag']
['yoghurt', 'krydderi']
[]
[]
['øl']
[]
[]
[]
['salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'yoghurtdressing', 'pommes frites', 'mayonnaise', 'sodavand']
['salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'yoghurtdressing', 'pommes frites', 'mayonnaise', 'sodavand']
['pommes frites', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'yoghurtdressing', 'mayonnaise', 'sodavand']
[]
[]
['salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'yoghurtdressing']
['salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'yoghurtdressing']
['pommes frites', 'salat', 'rødkål', 'rødløg', 'tomat', 'agurk', 'yoghurtdressing']
['nudelsalat', 'oksekød', 'forårsrulle', 'grøntsag', 'krydderurt', 'ristede løg', 'fiskesauce']
['forårsrulle', 'svinekød', 'glasnudel', 'grøntsag', 'salat', 'mynte', 'fiskesauce']
['kylling', 'grøntsag', 'sojasauce']
['tigerreje', 'risnudel', 'koriander', 'mynte', 'hoisin', 'peanutsauce']
['wonton', 'grøntsag', 'sojasauce']
['wonton', 'sommerrulle', 'forårsrulle', 'samosa', 'sojasauce', 'hoisin', 'peanutsauce']
['oksekød', 'risnudel', 'grøntsag', 'krydderurt', 'peanut', 'ristede løg', 'fiskesauce']
['risnudel', 'grøntsag', 'krydderurt', 'peanut', 'ristede løg', 'fiskesauce', 'forårsrulle']
['risnudel', 'grøntsag', 'krydderurt', 'peanut', 'ristede løg', 'fiskesauce', 'svinekød', 'citrongræs']
['svinekød', 'citrongræs', 'ris', 'agurk', 'spidskål', 'krydderurt', 'gulerod']
['oksekød', 'salat', 'krydderurt', 'ris']
['kylling', 'karry', 'gulerod', 'bønnespire', 'forårsløg', 'ris']
['nudelsalat', 'wonton', 'risnudel', 'grøntsag', 'krydderurt', 'peanut', 'sojasauce']
[]
[]
[]
['pommes frites']
['dürüm', 'pommes frites', 'sodavand']
['chili', 'ost', 'mayonnaise']
['mozzarella stick', 'mayonnaise']
['løgring', 'mayonnaise']
['mayonnaise']
['hummus', 'tzatziki']
['kebab', 'pommes frites', 'salat', 'dressing', 'tzatziki', 'hummus']
['kylling', 'pommes frites', 'salat', 'dressing', 'tzatziki', 'hummus']
['falafel', 'pommes frites', 'salat', 'dressing', 'tzatziki', 'hummus']
['børek', 'ost', 'spinat']
[]
[]
[]
[]
[]
[]
[]
[]
[]
['pitabrød', 'pommes frites', 'sodavand']
['pommes frites', 'dressing', 'tzatziki', 'hummus']
['dürüm']
[]
[]
['pitabrød']
[]
[]
[]
['brød', 'smør']
['salat', 'ært', 'tomat', 'gulerod', 'oliven', 'dressing']
['dip']
['mozzarella', 'løg', 'dip']
['dip']
['pepperoni', 'oksekød', 'skinke', 'champignon', 'løg', 'rød peberfrugt']
['pepperoni', 'oksekød', 'skinke', 'champignon', 'løg', 'rød peberfrugt']
['reje', 'tun', 'champignon']
['reje', 'tun', 'champignon']
['skinke', 'champignon']
['skinke', 'champignon']
['pepperoni', 'rød peberfrugt', 'champignon']
['pepperoni', 'rød peberfrugt', 'champignon']
['pepperoni', 'oksekød', 'skinke', 'bacon']
['pepperoni', 'oksekød', 'skinke', 'bacon']
['kebab', 'tomat', 'agurk', 'icebergsalat', 'creme fraiche']
['kebab', 'tomat', 'agurk', 'icebergsalat', 'creme fraiche']
['champignon', 'ananas', 'rød peberfrugt', 'løg', 'majs', 'ært', 'oliven']
['champignon', 'ananas', 'rød peberfrugt', 'løg', 'majs', 'ært', 'oliven']
['mozzarella', 'tomatsauce']
['mozzarella', 'tomatsauce']
['oksekød', 'pepperoni', 'løg', 'champignon', 'bbq-sauce']
['oksekød', 'pepperoni', 'løg', 'champignon', 'bbq-sauce']
['bacon', 'løg', 'majs']
['bacon', 'løg', 'majs']
['oksekød', 'jalapeño', 'løg']
['oksekød', 'jalapeño', 'løg']
['skinke', 'ananas']
['skinke', 'ananas']
['kylling', 'rød peberfrugt', 'løg']
['kylling', 'rød peberfrugt', 'løg']
['pepperoni']
['pepperoni']
['oksekød', 'champignon', 'rød peberfrugt']
['oksekød', 'champignon', 'rød peberfrugt']
['salat', 'ært', 'majs', 'tomat', 'gulerod', 'oliven', 'creme fraiche', 'thousand island dressing']
['rødspætte', 'salat', 'pommes frites', 'remoulade']
['parmesan']
['kylling', 'tomatsauce', 'parmesan']
['salat', 'pommes frites', 'bagt kartoffel']
['salat', 'pommes frites', 'bagt kartoffel']
['grøntsag', 'salat', 'pommes frites', 'bagt kartoffel']
['oksekød', 'salat', 'løg', 'tomat', 'agurk', 'creme fraiche dressing']
['oksekød', 'salat', 'løg', 'tomat', 'agurk', 'creme fraiche dressing']
['oksekød', 'pommes frites', 'salat', 'løg', 'tomat', 'agurk', 'creme fraiche']
['oksekød', 'tomat', 'løg', 'salat', 'ketchup']
['burgerbolle', 'oksekød', 'bacon', 'cheddar', 'bbq-sauce']
['burgerbolle', 'oksekød', 'cheddar', 'jalapeño', 'løgring', 'chilimayo']
['burgerbolle', 'kylling', 'cheddar', 'mayonnaise']
['burgerbolle', 'rødspætte', 'remoulade']
['burgerbolle', 'grøntsagsbøf', 'cheddar', 'mayonnaise']
['parmesan']
['mozzarella', 'pepperoni', 'skinke']
['rødspætte', 'pommes frites', 'remoulade']
['flødeskum', 'vaniljeis']
['flødeskum', 'chokoladesauce']
['flødeskum', 'vaniljeis']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['tomat', 'ost', 'pepperoni', 'kødsauce', 'ananas', 'chili']
['fladbrød', 'kebab', 'salat', 'dressing']
['fladbrød', 'kylling', 'salat', 'dressing']
['fladbrød', 'kebab', 'kylling', 'salat', 'dressing']
['fladbrød', 'falafel', 'salat', 'dressing']
['pitabrød', 'kebab', 'salat', 'dressing']
['pitabrød', 'kylling', 'salat', 'dressing']
['pitabrød', 'kebab', 'kylling', 'salat', 'dressing']
['pitabrød', 'falafel', 'salat', 'dressing']
['kylling', 'pommes frites', 'salat', 'mayonnaise']
['tomat', 'ost']
[]
['kebab', 'salat', 'pommes frites', 'bearnaise']
['kylling', 'salat', 'pommes frites', 'bearnaise']
['oksekød', 'salat', 'pommes frites', 'dressing', 'bearnaise']
['oksekød', 'løg', 'salat', 'pommes frites', 'bearnaise']
[]
['falafel', 'salat', 'dressing', 'pommes frites', 'mayonnaise']
['salat', 'rucola', 'dressing', 'pesto', 'brød']
['salat', 'kylling', 'dressing', 'pesto', 'brød']
['salat', 'feta', 'oliven', 'dressing', 'pesto', 'brød']
['tomat', 'ost']
['tomat', 'ost', 'skinke']
['tomat', 'ost', 'skinke', 'ananas']
['tomat', 'ost', 'skinke', 'champignon']
['tomat', 'ost', 'kylling', 'peberfrugt', 'løg']
['tomat', 'ost', 'kødsauce', 'løg']
['tomat', 'ost', 'skinke', 'pepperoni']
['tomat', 'ost', 'kebab', 'peberfrugt']
['tomat', 'ost', 'skinke', 'bacon']
['tomat', 'ost', 'kødbolle', 'peberfrugt', 'løg']
['tomat', 'ost', 'pepperoni', 'gorgonzola']
['tomat', 'ost', 'tun', 'champignon', 'løg']
['tomat', 'ost', 'kebab', 'champignon']
['tomat', 'ost', 'kylling', 'pesto', 'rucola']
['tomat', 'ost', 'pepperoni', 'kødbolle', 'jalapeño', 'ananas', 'hvidløg']
['tomat', 'ost', 'kartoffel', 'bacon', 'pepperoni', 'feta']
['tomat', 'ost', 'pepperoni']
['tomat', 'ost', 'skinke', 'pepperoni', 'bacon', 'pølse']
['tomat', 'ost', 'kebab', 'salat', 'dressing']
['tomat', 'ost', 'kylling', 'salat', 'dressing']
['tomat', 'ost', 'kødbolle', 'grøn peber', 'champignon', 'hvidløg']
['tomat', 'ost', 'kebab', 'champignon', 'gorgonzola', 'løg']
['tomat', 'ost', 'pepperoni', 'bacon', 'pølse']
['tomat', 'ost', 'kartoffel', 'kebab', 'pesto']
['tomat', 'ost', 'kebab', 'champignon', 'peberfrugt']
['tomat', 'ost', 'kebab', 'champignon', 'peberfrugt', 'løg', 'rucola', 'pesto']
['tomat', 'ost', 'kødbolle', 'pepperoni', 'løg', 'grøn peber', 'chili', 'hvidløg']
['tomat', 'ost', 'champignon', 'peberfrugt', 'løg', 'artiskok', 'hvidløg']
['tomat', 'ost', 'artiskok', 'kartoffel', 'pesto']
['tomat', 'ost', 'feta', 'løg', 'oliven', 'hvidløg']
['tomat', 'ost', 'kartoffel', 'feta', 'løg']
['tomat', 'ost', 'skinke', 'bacon', 'pepperoni', 'jalapeño']
['tomat', 'ost', 'bacon', 'pepperoni', 'jalapeño', 'chili']
['tomat', 'ost', 'kylling', 'peberfrugt', 'kebab', 'jalapeño', 'tacosauce']
['tomat', 'ost', 'skinke', 'champignon', 'tomatsauce']
['oksekød', 'salat', 'rucola', 'aioli', 'chilimayo']
['oksekød', 'salat', 'aioli', 'chilimayo']
['oksekød', 'salat', 'ost', 'aioli', 'chilimayo', 'tacosauce', 'jalapeño']
['kylling', 'salat', 'aioli', 'chilimayo']
['ost', 'salat', 'dressing']
[]
[]
[]
[]
[]
['tomat', 'ost', 'hvidløg']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['oksekød', 'salat', 'ost', 'aioli', 'chilimayo']
['oksekød', 'salat', 'bacon', 'aioli', 'chilimayo']
['oksekød', 'salat', 'bacon', 'ost', 'aioli', 'chilimayo']
['fladbrød', 'kylling', 'bacon', 'salat', 'dressing']
[]
[]
[]
['kylling']
['tomat', 'ost', 'kebab', 'pepperoni', 'feta', 'oliven', 'dressing', 'chilisauce']
['pommes frites', 'dip', 'mozzarella stick', 'chili', 'ost', 'nuggets']
[]
[]
['forårsrulle', 'grøntsag', 'sød chilisauce']
['kyllingevinge', 'sød chilisauce']
['reje', 'dej', 'sød chilisauce']
[]
['salat', 'oksekød', 'grøntsag', 'citrongræs', 'teriyaki']
[]
[]
['pad thai', 'nudel', 'æg', 'reje', 'peanut']
['pad thai', 'nudel', 'æg', 'kylling', 'grøntsag']
['nudel', 'sojasauce', 'æg', 'kylling', 'grøntsag']
['nudelsuppe', 'oksekød']
[]
['suppe', 'kokosmælk', 'kylling', 'galangarod', 'champignon', 'citrongræs', 'koriander']
['suppe', 'kokosmælk', 'reje', 'galangarod', 'champignon', 'citrongræs', 'koriander']
[]
['dumpling', 'svinekød', 'grøntsag']
['tom yum', 'suppe', 'kylling', 'galangarod', 'chili', 'champignon', 'koriander']
['tom yum', 'suppe', 'reje', 'galangarod', 'chili', 'champignon', 'koriander']
['tofu', 'sursød sauce', 'grøntsag']
['rød karry', 'tofu', 'kokosmælk', 'bambusskud', 'thaibasilikum']
['grøn karry', 'tofu', 'kokosmælk', 'thaiaubergine', 'limeblad', 'basilikum']
['panang karry', 'tofu', 'kokosmælk', 'grøntsag', 'limeblad']
[]
['kylling']
['massaman karry', 'oksekød', 'kylling']
[]
['svinekød', 'broccoli']
[]
['fisk', 'sursød sauce']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['rød karry', 'kokosmælk', 'bambusskud', 'thaibasilikum', 'kylling']
['rød karry', 'kokosmælk', 'bambusskud', 'thaibasilikum', 'oksekød']
['rød karry', 'kokosmælk', 'bambusskud', 'thaibasilikum', 'reje']
['rød karry', 'kokosmælk', 'bambusskud', 'thaibasilikum', 'blæksprutte']
['grøn karry', 'kokosmælk', 'thaiaubergine', 'limeblad', 'basilikum', 'oksekød']